apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-bot
  namespace: filecoin-pay-auction-bot
  labels:
    app.kubernetes.io/name: auction-bot
    app.kubernetes.io/component: bot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: auction-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auction-bot
        app.kubernetes.io/component: bot
    spec:
      containers:
        - name: auction-bot
          image: filoz/auction-bot:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: auction-bot-env
            - secretRef:
                name: auction-bot-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
