apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-stats-env
  namespace: filecoin-pay-auction-bot
data:
  RPC_URL: 'https://api.calibration.node.glif.io/'
  STATS_INTERVAL: '60000'
  METRICS_PORT: '9090'
