apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-bot
  namespace: auction-bot
spec:
  template:
    spec:
      containers:
      - name: auction-bot
        image: auction-bot:local
        imagePullPolicy: Never
